### PR TITLE
Add php 7.0 and add support of crontab

### PR DESCRIPTION
**Pull request by nickspring**
I know, it's old version, however a lot of people still have old code which isn't compatible with versions > 7.0

### CODE REVIEW

**Comment by f3l1x** [comment]
Hi! Thank you for PR! It's totally OK, also I will add PHP 7.1 as well. ;-)

**Comment by nickspring** [comment]
Thanks! BTW why do you have the same nginx, php. supervisor configs for each version in each folder?

**Comment by nickspring** [comment]
I've added cron support to this Docker.

**Comment by f3l1x** [comment]
Hi @nickspring. Thank you, I will merge it and little refactor templates for nginx etc. Thank you for hints.

**Pull request merged**
